INSERT INTO Role (id,name) VALUES (1, 'ADMIN');
INSERT INTO Role (id,name) VALUES (2, 'PRICER');
INSERT INTO Role (id,name) VALUES (3, 'PLAYER');

INSERT INTO Player (id, email, enabled, password, username) VALUES (1,'jarriaga86@gmail.com',true,'$2a$11$YunhRSiqISvRJWB7OLPQHOVA7D4suJCmwBzVYk6GOvEYeYEFJbYPC','Shareef');
INSERT INTO Player_Role (playerId, roleId) VALUES (1,1);
INSERT INTO Player_Role (playerId, roleId) VALUES (1,2);
INSERT INTO Player_Role (playerId, roleId) VALUES (1,3);

INSERT INTO Category (id,name) VALUES (1,'Grand Tour');

INSERT INTO Race (id,name,categoryId) VALUES (1, 'Giro', 1);
INSERT INTO Race (id,name,categoryId) VALUES (2, 'Tour', 1);
INSERT INTO Race (id,name,categoryId) VALUES (3, 'Vuelta', 1);

INSERT INTO Country (id, code, name) VALUES  (1, 'AFG', 'Afghanistan');
INSERT INTO Country (id, code, name) VALUES  (2, 'ALB', 'Albania');
INSERT INTO Country (id, code, name) VALUES  (3, 'DZA', 'Algeria');
INSERT INTO Country (id, code, name) VALUES  (4, 'ASM', 'American Samoa');
INSERT INTO Country (id, code, name) VALUES  (5, 'AND', 'Andorra');
INSERT INTO Country (id, code, name) VALUES  (6, 'AGO', 'Angola');
INSERT INTO Country (id, code, name) VALUES  (7, 'AIA', 'Anguilla');
INSERT INTO Country (id, code, name) VALUES  (8, NULL, 'Antarctica');
INSERT INTO Country (id, code, name) VALUES  (9, 'ATG', 'Antigua and Barbuda');
INSERT INTO Country (id, code, name) VALUES  (10, 'ARG', 'Argentina');
INSERT INTO Country (id, code, name) VALUES  (11, 'ARM', 'Armenia');
INSERT INTO Country (id, code, name) VALUES  (12, 'ABW', 'Aruba');
INSERT INTO Country (id, code, name) VALUES  (13, 'AUS', 'Australia');
INSERT INTO Country (id, code, name) VALUES  (14, 'AUT', 'Austria');
INSERT INTO Country (id, code, name) VALUES  (15, 'AZE', 'Azerbaijan');
INSERT INTO Country (id, code, name) VALUES  (16, 'BHS', 'Bahamas');
INSERT INTO Country (id, code, name) VALUES  (17, 'BHR', 'Bahrain');
INSERT INTO Country (id, code, name) VALUES  (18, 'BGD', 'Bangladesh');
INSERT INTO Country (id, code, name) VALUES  (19, 'BRB', 'Barbados');
INSERT INTO Country (id, code, name) VALUES  (20, 'BLR', 'Belarus');
INSERT INTO Country (id, code, name) VALUES  (21, 'BEL', 'Belgium');
INSERT INTO Country (id, code, name) VALUES  (22, 'BLZ', 'Belize');
INSERT INTO Country (id, code, name) VALUES  (23, 'BEN', 'Benin');
INSERT INTO Country (id, code, name) VALUES  (24, 'BMU', 'Bermuda');
INSERT INTO Country (id, code, name) VALUES  (25, 'BTN', 'Bhutan');
INSERT INTO Country (id, code, name) VALUES  (26, 'BOL', 'Bolivia');
INSERT INTO Country (id, code, name) VALUES  (27, 'BIH', 'Bosnia and Herzegovina');
INSERT INTO Country (id, code, name) VALUES  (28, 'BWA', 'Botswana');
INSERT INTO Country (id, code, name) VALUES  (29, NULL, 'Bouvet Island');
INSERT INTO Country (id, code, name) VALUES  (30, 'BRA', 'Brazil');
INSERT INTO Country (id, code, name) VALUES  (31, NULL, 'British Indian Ocean Territory');
INSERT INTO Country (id, code, name) VALUES  (32, 'BRN', 'Brunei Darussalam');
INSERT INTO Country (id, code, name) VALUES  (33, 'BGR', 'Bulgaria');
INSERT INTO Country (id, code, name) VALUES  (34, 'BFA', 'Burkina Faso');
INSERT INTO Country (id, code, name) VALUES  (35, 'BDI', 'Burundi');
INSERT INTO Country (id, code, name) VALUES  (36, 'KHM', 'Cambodia');
INSERT INTO Country (id, code, name) VALUES  (37, 'CMR', 'Cameroon');
INSERT INTO Country (id, code, name) VALUES  (38, 'CAN', 'Canada');
INSERT INTO Country (id, code, name) VALUES  (39, 'CPV', 'Cape Verde');
INSERT INTO Country (id, code, name) VALUES  (40, 'CYM', 'Cayman Islands');
INSERT INTO Country (id, code, name) VALUES  (41, 'CAF', 'Central African Republic');
INSERT INTO Country (id, code, name) VALUES  (42, 'TCD', 'Chad');
INSERT INTO Country (id, code, name) VALUES  (43, 'CHL', 'Chile');
INSERT INTO Country (id, code, name) VALUES  (44, 'CHN', 'China');
INSERT INTO Country (id, code, name) VALUES  (45, NULL, 'Christmas Island');
INSERT INTO Country (id, code, name) VALUES  (46, NULL, 'Cocos (Keeling) Islands');
INSERT INTO Country (id, code, name) VALUES  (47, 'COL', 'Colombia');
INSERT INTO Country (id, code, name) VALUES  (48, 'COM', 'Comoros');
INSERT INTO Country (id, code, name) VALUES  (49, 'COG', 'Congo');
INSERT INTO Country (id, code, name) VALUES  (50, 'COD', 'Congo, the Democratic Republic of the');
INSERT INTO Country (id, code, name) VALUES  (51, 'COK', 'Cook Islands');
INSERT INTO Country (id, code, name) VALUES  (52, 'CRI', 'Costa Rica');
INSERT INTO Country (id, code, name) VALUES  (53, 'CIV', 'Cote D''Ivoire');
INSERT INTO Country (id, code, name) VALUES  (54, 'HRV', 'Croatia');
INSERT INTO Country (id, code, name) VALUES  (55, 'CUB', 'Cuba');
INSERT INTO Country (id, code, name) VALUES  (56, 'CYP', 'Cyprus');
INSERT INTO Country (id, code, name) VALUES  (57, 'CZE', 'Czech Republic');
INSERT INTO Country (id, code, name) VALUES  (58, 'DNK', 'Denmark');
INSERT INTO Country (id, code, name) VALUES  (59, 'DJI', 'Djibouti');
INSERT INTO Country (id, code, name) VALUES  (60, 'DMA', 'Dominica');
INSERT INTO Country (id, code, name) VALUES  (61, 'DOM', 'Dominican Republic');
INSERT INTO Country (id, code, name) VALUES  (62, 'ECU', 'Ecuador');
INSERT INTO Country (id, code, name) VALUES  (63, 'EGY', 'Egypt');
INSERT INTO Country (id, code, name) VALUES  (64, 'SLV', 'El Salvador');
INSERT INTO Country (id, code, name) VALUES  (65, 'GNQ', 'Equatorial Guinea');
INSERT INTO Country (id, code, name) VALUES  (66, 'ERI', 'Eritrea');
INSERT INTO Country (id, code, name) VALUES  (67, 'EST', 'Estonia');
INSERT INTO Country (id, code, name) VALUES  (68, 'ETH', 'Ethiopia');
INSERT INTO Country (id, code, name) VALUES  (69, 'FLK', 'Falkland Islands (Malvinas)');
INSERT INTO Country (id, code, name) VALUES  (70, 'FRO', 'Faroe Islands');
INSERT INTO Country (id, code, name) VALUES  (71, 'FJI', 'Fiji');
INSERT INTO Country (id, code, name) VALUES  (72, 'FIN', 'Finland');
INSERT INTO Country (id, code, name) VALUES  (73, 'FRA', 'France');
INSERT INTO Country (id, code, name) VALUES  (74, 'GUF', 'French Guiana');
INSERT INTO Country (id, code, name) VALUES  (75, 'PYF', 'French Polynesia');
INSERT INTO Country (id, code, name) VALUES  (76, NULL, 'French Southern Territories');
INSERT INTO Country (id, code, name) VALUES  (77, 'GAB', 'Gabon');
INSERT INTO Country (id, code, name) VALUES  (78, 'GMB', 'Gambia');
INSERT INTO Country (id, code, name) VALUES  (79, 'GEO', 'Georgia');
INSERT INTO Country (id, code, name) VALUES  (80, 'DEU', 'Germany');
INSERT INTO Country (id, code, name) VALUES  (81, 'GHA', 'Ghana');
INSERT INTO Country (id, code, name) VALUES  (82, 'GIB', 'Gibraltar');
INSERT INTO Country (id, code, name) VALUES  (83, 'GRC', 'Greece');
INSERT INTO Country (id, code, name) VALUES  (84, 'GRL', 'Greenland');
INSERT INTO Country (id, code, name) VALUES  (85, 'GRD', 'Grenada');
INSERT INTO Country (id, code, name) VALUES  (86, 'GLP', 'Guadeloupe');
INSERT INTO Country (id, code, name) VALUES  (87, 'GUM', 'Guam');
INSERT INTO Country (id, code, name) VALUES  (88, 'GTM', 'Guatemala');
INSERT INTO Country (id, code, name) VALUES  (89, 'GIN', 'Guinea');
INSERT INTO Country (id, code, name) VALUES  (90, 'GNB', 'Guinea-Bissau');
INSERT INTO Country (id, code, name) VALUES  (91, 'GUY', 'Guyana');
INSERT INTO Country (id, code, name) VALUES  (92, 'HTI', 'Haiti');
INSERT INTO Country (id, code, name) VALUES  (93, NULL, 'Heard Island and Mcdonald Islands');
INSERT INTO Country (id, code, name) VALUES  (94, 'VAT', 'Holy See (Vatican City State)');
INSERT INTO Country (id, code, name) VALUES  (95, 'HND', 'Honduras');
INSERT INTO Country (id, code, name) VALUES  (96, 'HKG', 'Hong Kong');
INSERT INTO Country (id, code, name) VALUES  (97, 'HUN', 'Hungary');
INSERT INTO Country (id, code, name) VALUES  (98, 'ISL', 'Iceland');
INSERT INTO Country (id, code, name) VALUES  (99, 'IND', 'India');
INSERT INTO Country (id, code, name) VALUES  (100, 'IDN', 'Indonesia');
INSERT INTO Country (id, code, name) VALUES  (101, 'IRN', 'Iran, Islamic Republic of');
INSERT INTO Country (id, code, name) VALUES  (102, 'IRQ', 'Iraq');
INSERT INTO Country (id, code, name) VALUES  (103, 'IRL', 'Ireland');
INSERT INTO Country (id, code, name) VALUES  (104, 'ISR', 'Israel');
INSERT INTO Country (id, code, name) VALUES  (105, 'ITA', 'Italy');
INSERT INTO Country (id, code, name) VALUES  (106, 'JAM', 'Jamaica');
INSERT INTO Country (id, code, name) VALUES  (107, 'JPN', 'Japan');
INSERT INTO Country (id, code, name) VALUES  (108, 'JOR', 'Jordan');
INSERT INTO Country (id, code, name) VALUES  (109, 'KAZ', 'Kazakhstan');
INSERT INTO Country (id, code, name) VALUES  (110, 'KEN', 'Kenya');
INSERT INTO Country (id, code, name) VALUES  (111, 'KIR', 'Kiribati');
INSERT INTO Country (id, code, name) VALUES  (112, 'PRK', 'Korea, Democratic People''s Republic of');
INSERT INTO Country (id, code, name) VALUES  (113, 'KOR', 'Korea, Republic of');
INSERT INTO Country (id, code, name) VALUES  (114, 'KWT', 'Kuwait');
INSERT INTO Country (id, code, name) VALUES  (115, 'KGZ', 'Kyrgyzstan');
INSERT INTO Country (id, code, name) VALUES  (116, 'LAO', 'Lao People''s Democratic Republic');
INSERT INTO Country (id, code, name) VALUES  (117, 'LVA', 'Latvia');
INSERT INTO Country (id, code, name) VALUES  (118, 'LBN', 'Lebanon');
INSERT INTO Country (id, code, name) VALUES  (119, 'LSO', 'Lesotho');
INSERT INTO Country (id, code, name) VALUES  (120, 'LBR', 'Liberia');
INSERT INTO Country (id, code, name) VALUES  (121, 'LBY', 'Libyan Arab Jamahiriya');
INSERT INTO Country (id, code, name) VALUES  (122, 'LIE', 'Liechtenstein');
INSERT INTO Country (id, code, name) VALUES  (123, 'LTU', 'Lithuania');
INSERT INTO Country (id, code, name) VALUES  (124, 'LUX', 'Luxembourg');
INSERT INTO Country (id, code, name) VALUES  (125, 'MAC', 'Macao');
INSERT INTO Country (id, code, name) VALUES  (126, 'MKD', 'Macedonia, the Former Yugoslav Republic of');
INSERT INTO Country (id, code, name) VALUES  (127, 'MDG', 'Madagascar');
INSERT INTO Country (id, code, name) VALUES  (128, 'MWI', 'Malawi');
INSERT INTO Country (id, code, name) VALUES  (129, 'MYS', 'Malaysia');
INSERT INTO Country (id, code, name) VALUES  (130, 'MDV', 'Maldives');
INSERT INTO Country (id, code, name) VALUES  (131, 'MLI', 'Mali');
INSERT INTO Country (id, code, name) VALUES  (132, 'MLT', 'Malta');
INSERT INTO Country (id, code, name) VALUES  (133, 'MHL', 'Marshall Islands');
INSERT INTO Country (id, code, name) VALUES  (134, 'MTQ', 'Martinique');
INSERT INTO Country (id, code, name) VALUES  (135, 'MRT', 'Mauritania');
INSERT INTO Country (id, code, name) VALUES  (136, 'MUS', 'Mauritius');
INSERT INTO Country (id, code, name) VALUES  (137, NULL, 'Mayotte');
INSERT INTO Country (id, code, name) VALUES  (138, 'MEX', 'Mexico');
INSERT INTO Country (id, code, name) VALUES  (139, 'FSM', 'Micronesia, Federated States of');
INSERT INTO Country (id, code, name) VALUES  (140, 'MDA', 'Moldova, Republic of');
INSERT INTO Country (id, code, name) VALUES  (141, 'MCO', 'Monaco');
INSERT INTO Country (id, code, name) VALUES  (142, 'MNG', 'Mongolia');
INSERT INTO Country (id, code, name) VALUES  (143, 'MSR', 'Montserrat');
INSERT INTO Country (id, code, name) VALUES  (144, 'MAR', 'Morocco');
INSERT INTO Country (id, code, name) VALUES  (145, 'MOZ', 'Mozambique');
INSERT INTO Country (id, code, name) VALUES  (146, 'MMR', 'Myanmar');
INSERT INTO Country (id, code, name) VALUES  (147, 'NAM', 'Namibia');
INSERT INTO Country (id, code, name) VALUES  (148, 'NRU', 'Nauru');
INSERT INTO Country (id, code, name) VALUES  (149, 'NPL', 'Nepal');
INSERT INTO Country (id, code, name) VALUES  (150, 'NLD', 'Netherlands');
INSERT INTO Country (id, code, name) VALUES  (151, 'ANT', 'Netherlands Antilles');
INSERT INTO Country (id, code, name) VALUES  (152, 'NCL', 'New Caledonia');
INSERT INTO Country (id, code, name) VALUES  (153, 'NZL', 'New Zealand');
INSERT INTO Country (id, code, name) VALUES  (154, 'NIC', 'Nicaragua');
INSERT INTO Country (id, code, name) VALUES  (155, 'NER', 'Niger');
INSERT INTO Country (id, code, name) VALUES  (156, 'NGA', 'Nigeria');
INSERT INTO Country (id, code, name) VALUES  (157, 'NIU', 'Niue');
INSERT INTO Country (id, code, name) VALUES  (158, 'NFK', 'Norfolk Island');
INSERT INTO Country (id, code, name) VALUES  (159, 'MNP', 'Northern Mariana Islands');
INSERT INTO Country (id, code, name) VALUES  (160, 'NOR', 'Norway');
INSERT INTO Country (id, code, name) VALUES  (161, 'OMN', 'Oman');
INSERT INTO Country (id, code, name) VALUES  (162, 'PAK', 'Pakistan');
INSERT INTO Country (id, code, name) VALUES  (163, 'PLW', 'Palau');
INSERT INTO Country (id, code, name) VALUES  (164, NULL, 'Palestinian Territory, Occupied');
INSERT INTO Country (id, code, name) VALUES  (165, 'PAN', 'Panama');
INSERT INTO Country (id, code, name) VALUES  (166, 'PNG', 'Papua New Guinea');
INSERT INTO Country (id, code, name) VALUES  (167, 'PRY', 'Paraguay');
INSERT INTO Country (id, code, name) VALUES  (168, 'PER', 'Peru');
INSERT INTO Country (id, code, name) VALUES  (169, 'PHL', 'Philippines');
INSERT INTO Country (id, code, name) VALUES  (170, 'PCN', 'Pitcairn');
INSERT INTO Country (id, code, name) VALUES  (171, 'POL', 'Poland');
INSERT INTO Country (id, code, name) VALUES  (172, 'PRT', 'Portugal');
INSERT INTO Country (id, code, name) VALUES  (173, 'PRI', 'Puerto Rico');
INSERT INTO Country (id, code, name) VALUES  (174, 'QAT', 'Qatar');
INSERT INTO Country (id, code, name) VALUES  (175, 'REU', 'Reunion');
INSERT INTO Country (id, code, name) VALUES  (176, 'ROM', 'Romania');
INSERT INTO Country (id, code, name) VALUES  (177, 'RUS', 'Russian Federation');
INSERT INTO Country (id, code, name) VALUES  (178, 'RWA', 'Rwanda');
INSERT INTO Country (id, code, name) VALUES  (179, 'SHN', 'Saint Helena');
INSERT INTO Country (id, code, name) VALUES  (180, 'KNA', 'Saint Kitts and Nevis');
INSERT INTO Country (id, code, name) VALUES  (181, 'LCA', 'Saint Lucia');
INSERT INTO Country (id, code, name) VALUES  (182, 'SPM', 'Saint Pierre and Miquelon');
INSERT INTO Country (id, code, name) VALUES  (183, 'VCT', 'Saint Vincent and the Grenadines');
INSERT INTO Country (id, code, name) VALUES  (184, 'WSM', 'Samoa');
INSERT INTO Country (id, code, name) VALUES  (185, 'SMR', 'San Marino');
INSERT INTO Country (id, code, name) VALUES  (186, 'STP', 'Sao Tome and Principe');
INSERT INTO Country (id, code, name) VALUES  (187, 'SAU', 'Saudi Arabia');
INSERT INTO Country (id, code, name) VALUES  (188, 'SEN', 'Senegal');
INSERT INTO Country (id, code, name) VALUES  (189, NULL, 'Serbia and Montenegro');
INSERT INTO Country (id, code, name) VALUES  (190, 'SYC', 'Seychelles');
INSERT INTO Country (id, code, name) VALUES  (191, 'SLE', 'Sierra Leone');
INSERT INTO Country (id, code, name) VALUES  (192, 'SGP', 'Singapore');
INSERT INTO Country (id, code, name) VALUES  (193, 'SVK', 'Slovakia');
INSERT INTO Country (id, code, name) VALUES  (194, 'SVN', 'Slovenia');
INSERT INTO Country (id, code, name) VALUES  (195, 'SLB', 'Solomon Islands');
INSERT INTO Country (id, code, name) VALUES  (196, 'SOM', 'Somalia');
INSERT INTO Country (id, code, name) VALUES  (197, 'ZAF', 'South Africa');
INSERT INTO Country (id, code, name) VALUES  (198, NULL, 'South Georgia and the South Sandwich Islands');
INSERT INTO Country (id, code, name) VALUES  (199, 'ESP', 'Spain');
INSERT INTO Country (id, code, name) VALUES  (200, 'LKA', 'Sri Lanka');
INSERT INTO Country (id, code, name) VALUES  (201, 'SDN', 'Sudan');
INSERT INTO Country (id, code, name) VALUES  (202, 'SUR', 'Suriname');
INSERT INTO Country (id, code, name) VALUES  (203, 'SJM', 'Svalbard and Jan Mayen');
INSERT INTO Country (id, code, name) VALUES  (204, 'SWZ', 'Swaziland');
INSERT INTO Country (id, code, name) VALUES  (205, 'SWE', 'Sweden');
INSERT INTO Country (id, code, name) VALUES  (206, 'CHE', 'Switzerland');
INSERT INTO Country (id, code, name) VALUES  (207, 'SYR', 'Syrian Arab Republic');
INSERT INTO Country (id, code, name) VALUES  (208, 'TWN', 'Taiwan, Province of China');
INSERT INTO Country (id, code, name) VALUES  (209, 'TJK', 'Tajikistan');
INSERT INTO Country (id, code, name) VALUES  (210, 'TZA', 'Tanzania, United Republic of');
INSERT INTO Country (id, code, name) VALUES  (211, 'THA', 'Thailand');
INSERT INTO Country (id, code, name) VALUES  (212, NULL, 'Timor-Leste');
INSERT INTO Country (id, code, name) VALUES  (213, 'TGO', 'Togo');
INSERT INTO Country (id, code, name) VALUES  (214, 'TKL', 'Tokelau');
INSERT INTO Country (id, code, name) VALUES  (215, 'TON', 'Tonga');
INSERT INTO Country (id, code, name) VALUES  (216, 'TTO', 'Trinidad and Tobago');
INSERT INTO Country (id, code, name) VALUES  (217, 'TUN', 'Tunisia');
INSERT INTO Country (id, code, name) VALUES  (218, 'TUR', 'Turkey');
INSERT INTO Country (id, code, name) VALUES  (219, 'TKM', 'Turkmenistan');
INSERT INTO Country (id, code, name) VALUES  (220, 'TCA', 'Turks and Caicos Islands');
INSERT INTO Country (id, code, name) VALUES  (221, 'TUV', 'Tuvalu');
INSERT INTO Country (id, code, name) VALUES  (222, 'UGA', 'Uganda');
INSERT INTO Country (id, code, name) VALUES  (223, 'UKR', 'Ukraine');
INSERT INTO Country (id, code, name) VALUES  (224, 'ARE', 'United Arab Emirates');
INSERT INTO Country (id, code, name) VALUES  (225, 'GBR', 'United Kingdom');
INSERT INTO Country (id, code, name) VALUES  (226, 'USA', 'United States');
INSERT INTO Country (id, code, name) VALUES  (227, NULL, 'United States Minor Outlying Islands');
INSERT INTO Country (id, code, name) VALUES  (228, 'URY', 'Uruguay');
INSERT INTO Country (id, code, name) VALUES  (229, 'UZB', 'Uzbekistan');
INSERT INTO Country (id, code, name) VALUES  (230, 'VUT', 'Vanuatu');
INSERT INTO Country (id, code, name) VALUES  (231, 'VEN', 'Venezuela');
INSERT INTO Country (id, code, name) VALUES  (232, 'VNM', 'Viet Nam');
INSERT INTO Country (id, code, name) VALUES  (233, 'VGB', 'Virgin Islands, British');
INSERT INTO Country (id, code, name) VALUES  (234, 'VIR', 'Virgin Islands, U.s.');
INSERT INTO Country (id, code, name) VALUES  (235, 'WLF', 'Wallis and Futuna');
INSERT INTO Country (id, code, name) VALUES  (236, 'ESH', 'Western Sahara');
INSERT INTO Country (id, code, name) VALUES  (237, 'YEM', 'Yemen');
INSERT INTO Country (id, code, name) VALUES  (238, 'ZMB', 'Zambia');
INSERT INTO Country (id, code, name) VALUES  (239, 'ZWE', 'Zimbabwe');

INSERT INTO Team (id, basicName) VALUES (1,'Abarca Sports');